apiVersion: v1
kind: Service
metadata:
  labels:
    app: reg-app
  name: registration
spec:
  type: LoadBalancer
  selector:
    app: reg-app
  ports:
    - name: 'http'
      port: 8181
      targetPort: 8080
